# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import idgo_resource.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idgo_resource', '0003_storageresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, db_column='file', null=True, upload_to=idgo_resource.models._ftp_file_upload_to, verbose_name='Fichier')),
                ('resource', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_resource.Resource')),
            ],
            options={
                'verbose_name': 'Répertoire de données issu du FTP.',
                'verbose_name_plural': 'Répertoire de données issus du FTP.',
                'db_table': 'idgo_store_ftp',
            },
        ),
        migrations.CreateModel(
            name='StoreUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, db_column='file', null=True, upload_to=idgo_resource.models._ftp_file_upload_to, verbose_name='Fichier')),
                ('resource', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idgo_resource.Resource')),
            ],
            options={
                'verbose_name': 'Répertoire de données téléversée',
                'verbose_name_plural': 'Répertoire de données téléversées',
                'db_table': 'idgo_store_upload',
            },
        ),
    ]
